Controllers films users
PVD777/java-filmorate pull request #5
Opened 2023-03-18 11:55 UTC by PVD777

2023-03-18 20:27 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new ValidationException("Фильм с таким id не существует");
Будь внимателен с форматированием и кавычками. Сейчас словно throw должен быть внутри else, но на самом деле он не входит в else, т.к. нет фигурных скобок

2023-03-18 20:32 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User updateFilm (@RequestBody @Valid User user) {
Метод лучше называть так, чтобы было понятно что он делает. Данный метод обновляет пользователя, а не фильм

2023-03-18 20:36 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film addFilm (@RequestBody @Valid Film film) {
Не проходит запрос
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"Film2Name",
	"description":"2descriptionItem",
	"duration": 222,
	"releaseDate": "2012-04-23T18:25:43.511Z",
	"mpa":{
	  "id":"1",
		"name":"2223"
},
	"genres":	[{"id":"1", "name":"genreName"}]
}'

Если есть желание, попробуй сделать так, чтобы пользователю возвращался ответ, в котором будет написано что конкретно не проходит
{
	"timestamp": "2023-03-18T20:35:33.336+00:00",
	"status": 400,
	"error": "Bad Request",
	"path": "/films"
}

2023-03-18 20:37 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложение по улучшению кода

2023-03-19 17:21 UTC, PVD777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new ValidationException("Фильм с таким id не существует");
+{}
fixed

2023-03-19 17:21 UTC, PVD777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User updateFilm (@RequestBody @Valid User user) {
updateFilm -> updateUser
fixed

2023-03-19 17:22 UTC, PVD777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film addFilm (@RequestBody @Valid Film film) {
add annotation to releaseDate in Film class

2023-03-19 20:06 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-03-21 17:55 UTC, merged