added db storages
PVD777/java-filmorate pull request #9
Opened 2023-04-16 22:21 UTC by PVD777

added db storages

2023-04-16 23:54 UTC, EvgenyKoptubenko commented
<img width="676" alt="image" src="https://user-images.githubusercontent.com/104884841/232350636-48b1e336-925d-4ff6-a15e-1d3d85111488.png">
Такая связь не понятно. В одной таблице не может быть двух идентификаторов.
Если нужно сделать много ко многим, то нужно сделать промежуточную таблицу, а эти две будут относиться к ней как один ко многим

2023-04-17 00:00 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public ErrorResponse handleGenreNotFound(GenreNotFoundException e) {
Тут много функций, которые дублируют друг друга, разница только в логировании. Но при этом эта строка с ошибкой есть внутри. А сами обработчики можно объединить, написан эксепшены через запятую

2023-04-17 00:05 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setGenres(genreStorage.getFilmGenres(film.getId()));
Если есть желание, попробуй переписать запрос так, чтобы для выборки фильмов использовалось не 5 запросов, а один.
Это позволит сократить количество запросов к базе данных

2023-04-17 00:08 UTC, EvgenyKoptubenko commented
Если отправить такой запрос, то падает 500
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"FilmName",
	"email":"email@email.com",
  "login":"login",
	"birthday":"2001-01-01",
	"duration":22
}'

{
	"error": "HV000028: Unexpected exception during isValid call."
}

2023-04-17 00:09 UTC, EvgenyKoptubenko commented
Если отправить такой запрос, то тоже 500, но должен быть Bad Request
curl --request PUT \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"wrong_emailmail.com",
  "login":"login22",
	"birthday":"2012-04-23T18:25:43.511Z"
}'

{
	"error": "JSON parse error: Cannot deserialize value of type `java.time.LocalDate` from String \"2012-04-23T18:25:43.511Z\": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '2012-04-23T18:25:43.511Z' could not be parsed, unparsed text found at index 10; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDate` from String \"2012-04-23T18:25:43.511Z\": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '2012-04-23T18:25:43.511Z' could not be parsed, unparsed text found at index 10\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 5, column: 13] (through reference chain: ru.yandex.practicum.filmorate.model.User[\"birthday\"])"
}

2023-04-17 00:10 UTC, EvgenyKoptubenko commented
От такого запроса тоже падает 500, но это исправление не обязательно
curl --request PUT \
  --url http://localhost:8080/films/1/like/aaa \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"email3@email.com"
}'

2023-04-17 00:11 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть немного предложений по исправлению

2023-04-18 18:53 UTC, PVD777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public ErrorResponse handleGenreNotFound(GenreNotFoundException e) {
Fixed 
4 ExcHandler -> 1 handleObjectNotFound

2023-04-20 02:20 UTC, EvgenyKoptubenko approved these changes
Работа сделана нормально. Спасибо.

2023-04-24 17:15 UTC, merged